site_name: Dash Platform
plugins:
    - search:
    - redirects:
        redirect_maps:
            'SDK/README.md': 'https://dashplatform.readme.io/docs/dash-sdk-overview'
            'SDK/Overview.md': 'https://dashplatform.readme.io/docs/dash-sdk-overview'
            'SDK/examples/fetch-an-identity-from-its-name.md': 'https://dashplatform.readme.io/docs/dash-sdk-examples-fetch-an-identity-from-its-name'
