name: Publish docs via GitHub Pages
on:
  push:
    branches:
      # - main
      - mkdocs

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Collect docs
        run: |
          cp -r ./packages/js-dapi-client/docs/ ./docs/docs/DAPI-Client
          cp -r ./packages/js-dpp/docs/ ./docs/docs/DPP
          cp -r ./packages/js-dash-sdk/docs/ ./docs/docs/SDK
          cp -r ./packages/wallet-lib/docs/ ./docs/docs/Wallet-lib

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: optionaldomain.com
          CONFIG_FILE: docs/mkdocs.yml
          EXTRA_PACKAGES: build-base
          # GITHUB_DOMAIN: github.myenterprise.com
          # REQUIREMENTS: folder/requirements.txt
